2.1. Попередня обробка даних

In [1]:
import numpy as np
from sklearn import preprocessing

input_data = np.array([[5.1, -2.9, 3.3],
                       [-1.2, 7.8, -6.1],
                       [3.9, 0.4, 2.1],
                       [7.3, 9.9, -4.5]])

data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print("\nBinarized data:\n", data_binarized)

print("\nBEFORE: ")
print("Mean =", input_data.mean(axis=0))
print("Std deviation =", input_data.std(axis=0))

data_scaled = preprocessing.scale(input_data)
print("\nAFTER: ")
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis=0))

data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\nMin max scaled data:\n", data_scaled_minmax)

data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data, norm='l2')
print("\nL1 normalized data:\n", data_normalized_l1)
print("\nL2 normalized data:\n", data_normalized_l2)

input_labels = ['red', 'black', 'red', 'green', 'black', 'yellow', 'white']

encoder = preprocessing.LabelEncoder()
encoder.fit(input_labels)

print("\nLabel mapping:")
for i, item in enumerate(encoder.classes_):
    print(item, '-->', i)

test_labels = ['green', 'red', 'black']
encoded_values = encoder.transform(test_labels)
print("\nLabels =", test_labels)
print("Encoded values =", list(encoded_values))

encoded_values_dec = [3, 0, 4, 1]
decoded_list = encoder.inverse_transform(encoded_values_dec)
print("\nEncoded values =", encoded_values_dec)
print("Decoded labels =", list(decoded_list))


Binarized data:
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 0.]]

BEFORE: 
Mean = [ 3.775  3.8   -1.3  ]
Std deviation = [3.12039661 5.23593354 4.0620192 ]

AFTER: 
Mean = [1.11022302e-16 0.00000000e+00 2.77555756e-17]
Std deviation = [1. 1. 1.]

Min max scaled data:
 [[0.74117647 0.         1.        ]
 [0.         0.8359375  0.        ]
 [0.6        0.2578125  0.87234043]
 [1.         1.         0.17021277]]

L1 normalized data:
 [[ 0.45132743 -0.25663717  0.2920354 ]
 [-0.0794702   0.51655629 -0.40397351]
 [ 0.609375    0.0625      0.328125  ]
 [ 0.33640553  0.4562212  -0.20737327]]

L2 normalized data:
 [[ 0.75765788 -0.43082507  0.49024922]
 [-0.12030718  0.78199664 -0.61156148]
 [ 0.87690281  0.08993875  0.47217844]
 [ 0.55734935  0.75585734 -0.34357152]]

Label mapping:
black --> 0
green --> 1
red --> 2
white --> 3
yellow --> 4

Labels = ['green', 'red', 'black']
Encoded values = [np.int64(1), np.int64(2), np.int64(0)]

Encoded values = [3, 0, 4, 1]
Decoded labels = [np.str_('

2.2. Попередня обробка нових даних

In [3]:
import numpy as np
from sklearn import preprocessing

input_data = np.array([[4.6, 9.9, -3.5],
                       [-2.9, 4.1, -2.2],
                       [3.3, 8.8, -6.1],
                       [3.9, 1.4, 2.2]])

data_binarized = preprocessing.Binarizer(threshold=2.2).transform(input_data)
print("\nBinarized data:\n", data_binarized)

print("\nBEFORE: ")
print("Mean =", input_data.mean(axis=0))
print("Std deviation =", input_data.std(axis=0))

data_scaled = preprocessing.scale(input_data)
print("\nAFTER: ")
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis=0))

data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\nMin max scaled data:\n", data_scaled_minmax)

data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')
data_normalized_l2 = preprocessing.normalize(input_data, norm='l2')
print("\nL1 normalized data:\n", data_normalized_l1)
print("\nL2 normalized data:\n", data_normalized_l2)


Binarized data:
 [[1. 1. 0.]
 [0. 1. 0.]
 [1. 1. 0.]
 [1. 0. 0.]]

BEFORE: 
Mean = [ 2.225  6.05  -2.4  ]
Std deviation = [2.99447408 3.45723878 3.00416378]

AFTER: 
Mean = [-1.11022302e-16  1.11022302e-16  1.66533454e-16]
Std deviation = [1. 1. 1.]

Min max scaled data:
 [[1.         1.         0.31325301]
 [0.         0.31764706 0.46987952]
 [0.82666667 0.87058824 0.        ]
 [0.90666667 0.         1.        ]]

L1 normalized data:
 [[ 0.25555556  0.55       -0.19444444]
 [-0.31521739  0.44565217 -0.23913043]
 [ 0.18131868  0.48351648 -0.33516484]
 [ 0.52        0.18666667  0.29333333]]

L2 normalized data:
 [[ 0.40126114  0.86358375 -0.30530739]
 [-0.52893647  0.74780673 -0.40126215]
 [ 0.29452548  0.78540129 -0.54442589]
 [ 0.83129388  0.29841319  0.46893501]]
